// client_angular/src/app/app.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { MatToolbarModule } from '@angular/material/toolbar';
import { deriveKey, buildHeader, aadBytes, encryptUtf8, decryptUtf8, b64encode, b64decode } from './crypto';

const STORAGE_KEY = 'chaa_i_angular_client';
const MAX_LOG = 400;

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatToolbarModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatSlideToggleModule,
    MatButtonModule,
    MatIconModule
  ],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  private readonly fb = inject(FormBuilder);

  readonly configForm = this.fb.nonNullable.group({
    url: 'ws://localhost:8080/ws',
    userId: '',
    rooms: '',
    pass: '',
    useEncryption: true
  });

  readonly messageForm = this.fb.nonNullable.group({
    to: '',
    room: '',
    text: ''
  });

  readonly status = signal('Nicht verbunden');
  readonly statusClass = signal<'ok' | 'idle'>('idle');
  readonly logEntries = signal<string[]>([]);
  readonly connected = signal(false);

  private ws: WebSocket | null = null;
  private keyRing: CryptoKey[] = [];

  constructor() {
    this.restore();

    this.configForm.valueChanges.subscribe(() => {
      this.persist();
      if (!this.configForm.get('useEncryption')!.value) {
        this.keyRing = [];
      }
    });
  }

  private persist() {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(this.configForm.getRawValue()));
    } catch {
      /* noop */
    }
  }

  private restore() {
    try {
      const raw = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}');
      this.configForm.patchValue({
        url: raw.url || 'ws://localhost:8080/ws',
        userId: raw.userId || this.randomUserId(),
        rooms: raw.rooms || '',
        pass: raw.pass || '',
        useEncryption: raw.useEncryption !== false
      }, { emitEvent: false });
    } catch {
      this.configForm.patchValue({ userId: this.randomUserId() }, { emitEvent: false });
    }
  }

  private randomUserId() {
    return 'user-' + Math.random().toString(36).slice(2, 8);
  }

  appendLog(kind: string, payload: unknown) {
    const time = new Date().toLocaleTimeString();
    const text = `[${time}] ${kind}: ${typeof payload === 'string' ? payload : JSON.stringify(payload)}`;
    const next = [...this.logEntries(), text].slice(-MAX_LOG);
    this.logEntries.set(next);
    queueMicrotask(() => {
      const logger = document.getElementById('log');
      if (logger) logger.scrollTop = logger.scrollHeight;
    });
  }

  setConnected(flag: boolean) {
    this.connected.set(flag);
    this.status.set(flag ? 'Verbunden' : 'Nicht verbunden');
    this.statusClass.set(flag ? 'ok' : 'idle');
  }

  async connect() {
    const { url, userId, rooms, pass, useEncryption } = this.configForm.getRawValue();
    if (!url || !userId) {
      alert('URL und User-ID sind erforderlich');
      return;
    }

    this.keyRing = [];
    if (useEncryption) {
      if (!pass) {
        alert('Passphrase ist erforderlich');
        return;
      }
      try {
        this.keyRing.unshift(await deriveKey(pass));
      } catch {
        alert('Schluesselableitung fehlgeschlagen');
        return;
      }
    }

    try {
      this.ws?.close();
    } catch {
      /* noop */
    }

    const socket = new WebSocket(url);
    this.ws = socket;

    socket.addEventListener('open', () => {
      this.setConnected(true);
      this.appendLog('OPEN', url);
      const joinRooms = rooms
        ?.split(',')
        .map((token) => token.trim())
        .filter(Boolean);
      const join = { type: 'join', userId, rooms: joinRooms?.length ? joinRooms : undefined };
      socket.send(JSON.stringify(join));
      this.appendLog('SEND', join);
    });

    socket.addEventListener('message', async (event) => {
      let data: any;
      try {
        data = JSON.parse(event.data);
      } catch {
        this.appendLog('RECV', event.data);
        return;
      }

      if (data.type !== 'msg') {
        this.appendLog('RECV', data);
        return;
      }

      if (!this.configForm.get('useEncryption')!.value) {
        this.appendLog('RECV-PLAINTEXT', data);
        return;
      }

      try {
        if (!this.keyRing.length) throw new Error('Kein Schluessel');
        const { v, alg, from, to, room, ts, nonce, aad, ciphertext } = data;
        if (v !== 1 || alg !== 'aes-256-gcm-sha256') throw new Error('Unbekanntes v/alg');
        const aadBuffer = b64decode(aad);
        let ok = false;
        let plaintext = '';
        for (const candidate of this.keyRing) {
          try {
            plaintext = await decryptUtf8(ciphertext, nonce, candidate, aadBuffer);
            ok = true;
            break;
          } catch {
            /* continue */
          }
        }
        if (!ok) throw new Error('GCM-Auth-Fehler oder falscher Schluessel');
        this.appendLog('RECV-PLAINTEXT', { from, to, room, text: plaintext, ts });
      } catch (error) {
        this.appendLog('RECV-ERROR', String(error));
      }
    });

    socket.addEventListener('close', () => {
      this.appendLog('CLOSE', 'Verbindung geschlossen');
      this.setConnected(false);
    });

    socket.addEventListener('error', () => {
      this.appendLog('ERROR', 'WebSocket Fehler');
    });
  }

  disconnect() {
    try {
      this.ws?.close();
    } catch {
      /* noop */
    }
  }

  async applyPassphrase() {
    const pass = this.configForm.get('pass')!.value;
    if (!pass) {
      alert('Passphrase ist erforderlich');
      return;
    }
    try {
      const key = await deriveKey(pass);
      this.keyRing.unshift(key);
      if (this.keyRing.length > 5) this.keyRing.pop();
      this.appendLog('KEY-UPDATE', 'Passphrase angewendet');
    } catch {
      this.appendLog('KEY-ERROR', 'Schluesselableitung fehlgeschlagen');
    }
  }

  async sendMessage() {
    const socket = this.ws;
    if (!socket || socket.readyState !== WebSocket.OPEN) return;
    const { to, room, text } = this.messageForm.getRawValue();
    if (!to && !room) {
      alert('Bitte "An User" oder "An Room" ausfuellen.');
      return;
    }

    if (!this.configForm.get('useEncryption')!.value) {
      const payload: any = { type: 'msg', text, ts: Date.now() };
      if (to) payload.to = to;
      if (room) payload.room = room;
      socket.send(JSON.stringify(payload));
      this.appendLog('SEND', payload);
      return;
    }

    if (!this.keyRing.length) {
      alert('Kein Schluessel');
      return;
    }

    const header = buildHeader(
      this.configForm.get('userId')!.value,
      to || undefined,
      room || undefined
    );
    const aad = aadBytes(header);

    try {
      const { nonceB64, ciphertextB64 } = await encryptUtf8(text, this.keyRing[0], aad);
      const message = { type: 'msg', ...header, aad: b64encode(aad), nonce: nonceB64, ciphertext: ciphertextB64 };
      socket.send(JSON.stringify(message));
      this.appendLog('SEND', message);
    } catch (error) {
      this.appendLog('ENCRYPT-ERROR', String(error));
    }
  }
}

<mat-toolbar color="primary" class="toolbar">
  chaa-i · Angular Client
</mat-toolbar>

<div class="shell">
  <div class="column column--forms">
    <mat-card>
      <mat-card-title>Grundkonfiguration</mat-card-title>
      <mat-card-content [formGroup]="configForm" class="card-content">
        <div class="two-col">
          <mat-form-field appearance="outline">
            <mat-label>Serveradresse</mat-label>
            <input matInput formControlName="url" placeholder="ws://host:port/ws" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Username</mat-label>
            <input matInput formControlName="userId" />
          </mat-form-field>
        </div>
        <div class="two-col">
          <mat-form-field appearance="outline">
            <mat-label>Standard-Rooms (Komma)</mat-label>
            <input matInput formControlName="rooms" placeholder="z.B. general,dev" />
          </mat-form-field>
          <div class="toggle-row">
            <mat-slide-toggle formControlName="useEncryption">Verschluesselung aktiv</mat-slide-toggle>
          </div>
        </div>
        <ng-container *ngIf="configForm.get('useEncryption')!.value; else plaintextInfo">
          <div class="two-col">
            <mat-form-field appearance="outline">
              <mat-label>Passphrase</mat-label>
              <input matInput type="password" formControlName="pass" />
            </mat-form-field>
            <div class="pass-actions">
              <button mat-raised-button color="primary" (click)="applyPassphrase()">Passphrase anwenden</button>
              <span class="hint">Konfiguration wird lokal gespeichert.</span>
            </div>
          </div>
        </ng-container>
        <ng-template #plaintextInfo>
          <div class="note">Klartextmodus aktiv – Nachrichten werden ohne AES-GCM versendet.</div>
        </ng-template>
      </mat-card-content>
    </mat-card>

    <mat-card>
      <mat-card-title>Verbindung</mat-card-title>
      <mat-card-content class="card-content">
        <div class="button-row">
          <button mat-raised-button color="primary" (click)="connect()" [disabled]="connected()">Verbinden</button>
          <button mat-stroked-button color="primary" (click)="disconnect()" [disabled]="!connected()">Trennen</button>
          <span class="status" [class.ok]="statusClass() === 'ok'">{{ status() }}</span>
        </div>
      </mat-card-content>
    </mat-card>

    <mat-card>
      <mat-card-title>Nachricht senden</mat-card-title>
      <mat-card-content [formGroup]="messageForm" class="card-content">
        <div class="two-col">
          <mat-form-field appearance="outline">
            <mat-label>An User (optional)</mat-label>
            <input matInput formControlName="to" placeholder="userId" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>An Room (optional)</mat-label>
            <input matInput formControlName="room" placeholder="room" />
          </mat-form-field>
        </div>
        <mat-form-field appearance="outline" class="stretch">
          <mat-label>Nachricht</mat-label>
          <textarea matInput rows="4" formControlName="text" placeholder="Nachricht..."></textarea>
        </mat-form-field>
        <div class="button-row">
          <button mat-raised-button color="accent" (click)="sendMessage()" [disabled]="!connected()">Senden</button>
        </div>
      </mat-card-content>
    </mat-card>
  </div>

  <div class="column column--log">
    <mat-card class="log-card">
      <mat-card-title>Log</mat-card-title>
      <mat-card-content class="log-content">
        <div id="log">
          <div *ngFor="let entry of logEntries()">{{ entry }}</div>
        </div>
      </mat-card-content>
    </mat-card>
  </div>
</div>

// client_svelte/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { deriveKeyFromPassphrase, headerFor, aadBytesFor, encryptUtf8, decryptUtf8 } from '$lib/crypto';

  const CONFIG_KEY = 'chaa_i_svelte_client';
  const MAX_LOG = 400;

  let url = 'ws://localhost:8080/ws';
  let userId = '';
  let rooms = '';
  let to = '';
  let room = '';
  let text = '';
  let pass = '';
  let useEncryption = true;

  let status = 'Nicht verbunden';
  let connected = false;
  let statusClass = 'status';
  let log: string[] = [];
  let ws: WebSocket | null = null;
  let keyRing: CryptoKey[] = [];
  let configReady = false;

  function write(kind: string, payload: unknown) {
    const time = new Date().toLocaleTimeString();
    const message = `[${time}] ${kind}: ${typeof payload === 'string' ? payload : JSON.stringify(payload)}`;
    log = [...log.slice(-(MAX_LOG - 1)), message];
    queueMicrotask(() => {
      const el = document.getElementById('log');
      if (el) el.scrollTop = el.scrollHeight;
    });
  }

  function setConn(next: boolean) {
    connected = next;
    status = next ? 'Verbunden' : 'Nicht verbunden';
    statusClass = next ? 'status ok' : 'status';
  }

  function setKey(k: CryptoKey) {
    keyRing.unshift(k);
    if (keyRing.length > 5) keyRing.pop();
  }

  onMount(() => {
    try {
      const saved = JSON.parse(localStorage.getItem(CONFIG_KEY) || '{}');
      if (typeof saved.url === 'string' && saved.url) url = saved.url;
      if (typeof saved.userId === 'string' && saved.userId) userId = saved.userId;
      if (typeof saved.rooms === 'string') rooms = saved.rooms;
      if (typeof saved.pass === 'string') pass = saved.pass;
      if (typeof saved.useEncryption === 'boolean') useEncryption = saved.useEncryption;
    } catch {}
    if (!userId) userId = 'user-' + Math.random().toString(36).slice(2, 8);
    configReady = true;
  });

  $: if (configReady) {
    try {
      localStorage.setItem(
        CONFIG_KEY,
        JSON.stringify({ url, userId, rooms, pass, useEncryption })
      );
    } catch {}
  }

  $: if (!useEncryption) {
    keyRing = [];
  }

  async function connect() {
    if (!url || !userId) {
      alert('URL und User-ID sind erforderlich');
      return;
    }

    keyRing = [];
    if (useEncryption) {
      if (!pass) {
        alert('Passphrase ist erforderlich');
        return;
      }
      try {
        setKey(await deriveKeyFromPassphrase(pass));
      } catch {
        alert('Schluesselableitung fehlgeschlagen');
        return;
      }
    }

    try { ws?.close(); } catch {}
    ws = new WebSocket(url);

    ws.addEventListener('open', () => {
      setConn(true);
      write('OPEN', url);
      const list = rooms ? rooms.split(',').map((s) => s.trim()).filter(Boolean) : [];
      const join = { type: 'join', userId, rooms: list.length ? list : undefined };
      ws!.send(JSON.stringify(join));
      write('SEND', join);
    });

    ws.addEventListener('message', async (event) => {
      let data: any;
      try {
        data = JSON.parse(event.data);
      } catch {
        write('RECV', event.data);
        return;
      }

      if (data.type !== 'msg') {
        write('RECV', data);
        return;
      }

      if (!useEncryption) {
        write('RECV-PLAINTEXT', data);
        return;
      }

      try {
        if (!keyRing.length) throw new Error('Kein Schluessel');
        const { v, alg, from, to: dst, room: grp, ts, nonce, aad, ciphertext } = data;
        if (v !== 1 || alg !== 'aes-256-gcm-sha256') throw new Error('Unbekanntes v/alg');

        const aadBytes = Uint8Array.from(atob(aad), (c) => c.charCodeAt(0));
        let ok = false;
        let plaintext = '';
        for (const candidate of keyRing) {
          try {
            plaintext = await decryptUtf8(ciphertext, nonce, candidate, aadBytes);
            ok = true;
            break;
          } catch {}
        }
        if (!ok) throw new Error('GCM-Auth-Fehler oder falscher Schluessel');
        write('RECV-PLAINTEXT', { from, to: dst, room: grp, text: plaintext, ts });
      } catch (error) {
        write('RECV-ERROR', String(error));
      }
    });

    ws.addEventListener('close', () => {
      write('CLOSE', 'Verbindung geschlossen');
      setConn(false);
    });

    ws.addEventListener('error', () => {
      write('ERROR', 'WebSocket Fehler');
    });
  }

  function disconnect() {
    try { ws?.close(); } catch {}
  }

  async function applyPass() {
    if (!pass) {
      alert('Passphrase ist erforderlich');
      return;
    }
    try {
      const derived = await deriveKeyFromPassphrase(pass);
      setKey(derived);
      write('KEY-UPDATE', 'Passphrase angewendet');
    } catch {
      write('KEY-ERROR', 'Schluesselableitung fehlgeschlagen');
    }
  }

  async function send() {
    if (!ws || ws.readyState !== WebSocket.OPEN) return;
    if (!to && !room) {
      alert('Bitte "An User" oder "An Room" ausfuellen.');
      return;
    }

    if (!useEncryption) {
      const payload: any = { type: 'msg', text, ts: Date.now() };
      if (to) payload.to = to;
      if (room) payload.room = room;
      ws.send(JSON.stringify(payload));
      write('SEND', payload);
      return;
    }

    if (!keyRing.length) {
      alert('Kein Schluessel');
      return;
    }

    const header = headerFor(userId, to, room);
    const aadBytes = aadBytesFor(header);

    try {
      const { nonceB64, ciphertextB64 } = await encryptUtf8(text, keyRing[0], aadBytes);
      const aadB64 = btoa(String.fromCharCode(...aadBytes));
      const msg = { type: 'msg', ...header, aad: aadB64, nonce: nonceB64, ciphertext: ciphertextB64 };
      ws.send(JSON.stringify(msg));
      write('SEND', msg);
    } catch (error) {
      write('ENCRYPT-ERROR', String(error));
    }
  }
</script>

<style>
  :root { color-scheme: light dark; }
  main { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; margin: 16px; line-height: 1.35; }
  fieldset { border: 1px solid #8884; border-radius: 8px; padding: 14px; margin-bottom: 16px; }
  legend { padding: 0 6px; }
  label { display: block; margin: 6px 0 4px; font-size: .95rem; }
  input, textarea { width: 100%; padding: 8px; border: 1px solid #8886; border-radius: 6px; font-family: inherit; }
  textarea { min-height: 80px; }
  button { padding: 8px 12px; border-radius: 6px; border: 1px solid #6666; background: #eee; cursor: pointer; }
  button[disabled] { opacity: .6; cursor: not-allowed; }
  .grid-two { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 12px; }
  .inline { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; }
  .flow { display: flex; flex-direction: column; gap: 8px; }
  .hint { color: #666; font-size: .9rem; }
  .hint.small { font-size: .8rem; }
  .status { margin-top: 8px; font-size: .95rem; color: #a00; }
  .status.ok { color: #0a0; }
  .note { background: #0000000f; padding: 8px; border-radius: 6px; }
  #log { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; white-space: pre-wrap; background: #00000010; padding: 10px; border-radius: 8px; max-height: 45vh; overflow: auto; }
</style>

<main>
  <h1>chaa-i - Svelte Client</h1>
  <p class="hint">Unterstuetzt Klartext und AES-256-GCM (Passphrase -> SHA-256). Konfiguration wird lokal gespeichert.</p>

  <fieldset>
    <legend>Grundkonfiguration</legend>
    <div class="grid-two">
      <label>Serveradresse
        <input bind:value={url} placeholder="ws://host:port/ws" />
      </label>
      <label>Username
        <input bind:value={userId} />
      </label>
    </div>
    <div class="grid-two">
      <label>Standard-Rooms (Komma getrennt)
        <input bind:value={rooms} placeholder="z.b. general,dev" />
      </label>
      <label>
        <span>Verschluesselung</span>
        <div class="inline">
          <label><input type="checkbox" bind:checked={useEncryption} /> aktiv</label>
        </div>
      </label>
    </div>
    {#if useEncryption}
      <div class="grid-two">
        <label>Passphrase
          <input type="password" bind:value={pass} />
        </label>
        <div class="flow">
          <button on:click={applyPass}>Passphrase anwenden</button>
          <span class="hint small">Username, Serveradresse und Passphrase werden im Browser-Speicher abgelegt.</span>
        </div>
      </div>
    {:else}
      <div class="note hint small">Klartextmodus aktiv. Nachrichten werden ohne AES-GCM versendet.</div>
    {/if}
  </fieldset>

  <fieldset>
    <legend>Verbindung</legend>
    <div class="inline">
      <button on:click={connect} disabled={connected}>Verbinden</button>
      <button on:click={disconnect} disabled={!connected}>Trennen</button>
    </div>
    <div class={statusClass}>{status}</div>
  </fieldset>

  <fieldset>
    <legend>Nachricht senden</legend>
    <div class="grid-two">
      <label>An User (optional)
        <input bind:value={to} placeholder="userId" />
      </label>
      <label>An Room (optional)
        <input bind:value={room} placeholder="room" />
      </label>
    </div>
    <label>Nachricht
      <textarea bind:value={text} placeholder="Nachricht..."></textarea>
    </label>
    <div class="inline">
      <button on:click={send} disabled={!connected}>Senden</button>
    </div>
  </fieldset>

  <fieldset>
    <legend>Log</legend>
    <div id="log">{#each log as line}<div>{line}</div>{/each}</div>
  </fieldset>
</main>
